### ISSUE TITLE
[TODO] Recipes for common patterns and interactions in marketing websites

### ISSUE THREAD

**Issue by andrre-ls** [significa/foundations#30]
Ideas:
- [x] Horizontal scroll how-to
- [x] Scroll Parallax
- [ ] Pricing tables (maybe with CMS schema)
- [ ] Popover topnav
- [x] On-scroll stack with tabs
- [ ] General on-scroll animation guide
- [ ] 3D card on-mouse
- [x] "native" Slider with overflow scroll and scroll snap, that on pointer devices reads the scroll css properties and mimics the behavior with drag and pointer events

References:
- https://www.framer.com/
- https://payloadcms.com/
